---
- name: "Installing Wordpress"
  hosts: amazon
  become: true
  roles:
    - harden
    - lamp

  tasks: 
    
    - name: "Downloading Wordpress Archive"
      get_url:
        url: "{{ wp_url }}"
        dest: "/tmp/wordpress.tar.gz"

    - name: "Extracting Wordpress Archive"
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: "Copying worpress contents to Documentroot of {{ domain_name }}"
      copy:
        src: "/tmp/wordpress/"
        dest: "/var/www/html/{{ domain_name }}"
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"
        remote_src: yes

    - name: "Creating wp-config.php"
      template:
        src: wp-config.php.j2
        dest: "/var/www/html/{{ domain_name }}/wp-config.php"
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"

    - name: "Post-Installation - CleanUp"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/wordpress.tar.gz"
        - "/tmp/wordpress"

    - name: "Post-Installation - Restarting"
      service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items:
        - mariadb
        - httpd

